@startuml
'https://plantuml.com/class-diagram

class CarMechanic <Car> {
maxAmountOfCars : int
- final mechanicLoadingSystem : LoadingSystem<Car>
+ getAmountOfCarsInCarMechanic() : double
+ CarMechanic(int)
+ loadToMechanic(Car) : void
+ unLoad() : void
}

@enduml
